# Generated by Django 5.2.8 on 2025-11-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='user_name',
        ),
    ]
